(function (root) {
  "use strict";
  root.MindCoreLocales = root.MindCoreLocales || {};
  root.MindCoreLocales.ru = {
    "common.loading": "Загрузка...", "common.back": "Назад", "common.open": "Открыть", "common.close": "Закрыть", "common.save": "Сохранить", "common.retry": "Повторить", "common.edit": "Редактировать",
    "course.greeting": "Здравствуйте, {name}!", "date.invalid": "Некорректная дата",
    "startup.checking": "Проверяем доступ…", "startup.error": "Не удалось проверить доступ",
    "dashboard.title": "Кабинет курса", "dashboard.brand": "Бренд", "dashboard.student": "Студент", "dashboard.premium": "Премиум-доступ открыт", "dashboard.progressTitle": "Ваш прогресс", "dashboard.progress": "Пройдено: {completed} из {total}", "dashboard.lessons": "Уроки", "dashboard.loading": "Загрузка уроков...", "dashboard.empty": "Нет доступных уроков", "dashboard.error": "Ошибка загрузки данных", "dashboard.created": "Создано в MindCore", "dashboard.telegramAria": "Открыть MindCore в Telegram",
    "lesson.title": "Урок", "lesson.back": "Назад в кабинет", "lesson.loading": "Загрузка урока...", "lesson.namePlaceholder": "Название урока", "lesson.video": "Видео", "lesson.browser": "Откроется в браузере", "lesson.materials": "Материалы", "lesson.complete": "Отметить как пройдено", "lesson.completed": "Пройдено ✓", "lesson.day": "День {number}", "lesson.untitled": "Без названия", "lesson.descriptionMissing": "Описание отсутствует", "lesson.contentEmpty": "Содержимое урока пока пустое.", "lesson.notFoundId": "ID урока не найден. Откройте урок из списка.", "lesson.notFound": "Урок не найден для выбранного курса.", "lesson.unavailable": "Этот урок пока недоступен.", "lesson.openingNext": "Открываем следующий урок...", "lesson.loadError": "Не удалось загрузить урок.", "lesson.previewAlt": "Превью урока", "lesson.imageAlt": "Изображение урока", "lesson.material": "Материал {number}", "lesson.blocks": "{count} {word}", "lesson.block.one": "блок", "lesson.block.few": "блока", "lesson.block.many": "блоков", "lesson.statusDone": "Пройдено", "lesson.statusLocked": "Закрыто",
    "agreement.title": "Пользовательское соглашение", "agreement.accept": "Я принимаю условия соглашения", "agreement.continue": "Продолжить", "agreement.firstName": "Имя", "agreement.lastName": "Фамилия", "agreement.phone": "Телефон", "agreement.contacts": "Контактные данные", "agreement.saving": "Сохраняем…", "agreement.saveError": "Не удалось сохранить данные. Попробуйте ещё раз.", "agreement.loadError": "Не удалось загрузить соглашение", "agreement.retryHint": "Попробуйте повторить загрузку.",
    "forms.question": "Вопрос {number}", "forms.other": "Другое", "forms.otherPlaceholder": "Напишите свой вариант", "forms.aria": "Форма курса", "forms.defaultTitle": "Форма", "forms.yourForm": "Ваша {title}", "forms.viewAnswers": "Посмотреть ответы", "forms.recorded": "Зафиксировано {date}", "forms.answersSaved": "Ответы по форме сохранены.", "forms.answerSaved": "Ответ сохранён.", "forms.fill": "Заполнить", "forms.checking": "Проверяем сохранённые ответы…", "forms.loadError": "Не удалось загрузить ответы. Попробуйте обновить страницу.", "forms.otherRequired": "Заполните поле «{label}» или снимите выбор.", "forms.chooseOne": "Выберите хотя бы один вариант ответа.",
    "homework.unavailable": "Статус ДЗ недоступен", "homework.notSubmitted": "ДЗ не отправлено", "homework.pendingShort": "ДЗ на проверке", "homework.revisionShort": "Нужна доработка", "homework.acceptedShort": "ДЗ принято", "homework.checkError": "Не удалось проверить домашнее задание", "homework.checking": "Проверяем домашнее задание...", "homework.submitFirst": "Сначала отправьте домашнее задание", "homework.pendingGate": "Домашнее задание на проверке", "homework.revisionGate": "Требуется доработка", "homework.photo": "Фото", "homework.file": "Файл", "homework.video": "Видео", "homework.text": "Текст", "homework.addPhoto": "Добавить фото", "homework.addFile": "Добавить файл", "homework.addVideo": "Добавить видео", "homework.answer": "Ваш ответ", "homework.answerPlaceholder": "Напишите ответ...", "homework.pending": "На проверке", "homework.pendingText": "Домашнее задание отправлено и ожидает проверки.", "homework.accepted": "Принято", "homework.acceptedText": "Домашнее задание принято экспертом.", "homework.revision": "Нужна доработка", "homework.expertComment": "Комментарий эксперта", "homework.statusUnavailable": "Статус домашнего задания временно недоступен.", "homework.title": "Домашнее задание", "homework.canSend": "Можно отправить", "homework.submit": "Отправить домашнее задание", "homework.empty": "Добавьте ответ или прикрепите файл.", "homework.maxFiles": "Можно прикрепить не более 10 файлов.", "homework.emptyFile": "Файл «{name}» пустой.", "homework.unsupported": "Этот формат файла не поддерживается.", "homework.tooLarge": "Файл «{name}» слишком большой.", "homework.preparing": "Подготавливаем...", "homework.sending": "Отправляем...", "homework.uploading": "Загружаем {current} из {total}...", "homework.sendError": "Не удалось отправить домашнее задание. Попробуйте ещё раз.",
    "access.telegramTitle": "Откройте кабинет в Telegram", "access.telegramText": "Для проверки доступа откройте личный кабинет через кнопку в закрытом Telegram-канале.", "access.notFoundTitle": "Доступ не найден", "access.notFoundText": "Этот кабинет доступен только участникам программы.", "access.errorTitle": "Не удалось проверить доступ", "access.errorText": "Закройте кабинет и попробуйте открыть его снова чуть позже.", "access.expiredTitle": "Доступ к программе завершён", "access.expiredText": "Срок доступа к программе закончился. Чтобы продлить доступ, нажмите кнопку ниже.", "access.renew": "Продлить доступ", "access.expiredUntil": "Доступ был активен до: {date}",
    "renewal.expert": "Связаться с экспертом", "renewal.support": "Связаться с поддержкой", "renewal.creating": "Создаём заявку…", "renewal.conflict": "У вас уже есть незавершённая заявка на продление. Для изменения тарифа свяжитесь с поддержкой.", "renewal.payError": "Не удалось перейти к оплате. Попробуйте ещё раз.", "renewal.ended": "Доступ завершён", "renewal.soon": "Доступ скоро закончится", "renewal.endedTitle": "Доступ к программе завершён", "renewal.title": "Продлите доступ заранее", "renewal.lead": "Выберите вариант продления. После оплаты эксперт подтвердит её, и доступ откроется при следующем запуске кабинета.", "renewal.expertLead": "Чтобы продлить доступ, напишите эксперту в личные сообщения.", "renewal.wasUntil": "Доступ был активен до: {date}", "renewal.until": "Доступ открыт до: {date}", "renewal.days": "+{count} дней доступа", "renewal.choose": "Выбрать за {price}"
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
