(function (root) {
  "use strict";
  root.MindCoreLocales = root.MindCoreLocales || {};
  root.MindCoreLocales.tr = {
    "common.loading": "Yükleniyor...", "common.back": "Geri", "common.open": "Aç", "common.close": "Kapat", "common.save": "Kaydet", "common.retry": "Tekrar dene", "common.edit": "Düzenle",
    "course.greeting": "Merhaba, {name}!",
    "startup.checking": "Erişim kontrol ediliyor…", "startup.error": "Erişim kontrol edilemedi",
    "dashboard.title": "Kurs paneli", "dashboard.brand": "Marka", "dashboard.student": "Öğrenci", "dashboard.premium": "Premium erişim açık", "dashboard.progressTitle": "İlerlemeniz", "dashboard.progress": "Tamamlanan: {completed}/{total}", "dashboard.lessons": "Dersler", "dashboard.loading": "Dersler yükleniyor...", "dashboard.empty": "Kullanılabilir ders yok", "dashboard.error": "Veriler yüklenemedi", "dashboard.created": "MindCore ile oluşturuldu", "dashboard.telegramAria": "MindCore'u Telegram'da aç",
    "lesson.title": "Ders", "lesson.back": "Kurs paneline dön", "lesson.loading": "Ders yükleniyor...", "lesson.namePlaceholder": "Ders adı", "lesson.video": "Video", "lesson.browser": "Tarayıcıda açılır", "lesson.materials": "Materyaller", "lesson.complete": "Tamamlandı olarak işaretle", "lesson.completed": "Tamamlandı ✓", "lesson.day": "{number}. Gün", "lesson.untitled": "Adsız", "lesson.descriptionMissing": "Açıklama yok", "lesson.contentEmpty": "Bu dersin içeriği henüz boş.", "lesson.notFoundId": "Ders kimliği bulunamadı. Dersi listeden açın.", "lesson.notFound": "Seçilen kursta ders bulunamadı.", "lesson.unavailable": "Bu ders henüz kullanılamıyor.", "lesson.openingNext": "Sonraki ders açılıyor...", "lesson.loadError": "Ders yüklenemedi.", "lesson.previewAlt": "Ders önizlemesi", "lesson.imageAlt": "Ders görseli", "lesson.material": "Materyal {number}", "lesson.blocks": "{count} blok", "lesson.block.one": "blok", "lesson.block.few": "blok", "lesson.block.many": "blok", "lesson.statusDone": "Tamamlandı", "lesson.statusLocked": "Kilitli", "lesson.group.week": "HAFTA", "lesson.group.module": "MODÜL",
    "errors.supabaseClient": "Supabase istemcisi başlatılmadı. config.js ve supabase.js dosyalarını kontrol edin", "errors.lessonsLoad": "Supabase verileri yüklenemedi", "errors.lessonBlocksLoad": "Ders blokları yüklenemedi", "errors.lessonBlockGroupsLoad": "Ders materyali grupları yüklenemedi", "errors.blockItemsLoad": "Blok öğeleri yüklenemedi",
    "agreement.title": "Kullanıcı sözleşmesi", "agreement.accept": "Sözleşme koşullarını kabul ediyorum", "agreement.continue": "Devam et", "agreement.firstName": "Ad", "agreement.lastName": "Soyad", "agreement.phone": "Telefon", "agreement.contacts": "İletişim bilgileri", "agreement.saving": "Kaydediliyor…", "agreement.saveError": "Bilgiler kaydedilemedi. Tekrar deneyin.", "agreement.loadError": "Sözleşme yüklenemedi", "agreement.retryHint": "Yüklemeyi tekrar deneyin.",
    "forms.question": "Soru {number}", "forms.other": "Diğer", "forms.otherPlaceholder": "Kendi yanıtınızı yazın", "forms.aria": "Kurs formu", "forms.defaultTitle": "Form", "forms.yourForm": "{title}", "forms.viewAnswers": "Yanıtları görüntüle", "forms.recorded": "Kaydedildi: {date}", "forms.answersSaved": "Form yanıtları kaydedildi.", "forms.answerSaved": "Yanıt kaydedildi.", "forms.fill": "Doldur", "forms.checking": "Kaydedilmiş yanıtlar kontrol ediliyor…", "forms.loadError": "Yanıtlar yüklenemedi. Sayfayı yenileyin.", "forms.otherRequired": "«{label}» alanını doldurun veya seçimi kaldırın.", "forms.chooseOne": "En az bir yanıt seçin.",
    "homework.unavailable": "Ödev durumu kullanılamıyor", "homework.notSubmitted": "Ödev gönderilmedi", "homework.pendingShort": "Ödev inceleniyor", "homework.revisionShort": "Düzeltme gerekli", "homework.acceptedShort": "Ödev kabul edildi", "homework.checkError": "Ödev kontrol edilemedi", "homework.checking": "Ödev kontrol ediliyor...", "homework.submitFirst": "Önce ödevi gönderin", "homework.pendingGate": "Ödev inceleniyor", "homework.revisionGate": "Düzeltme gerekli", "homework.photo": "Fotoğraf", "homework.file": "Dosya", "homework.video": "Video", "homework.text": "Metin", "homework.addPhoto": "Fotoğraf ekle", "homework.addFile": "Dosya ekle", "homework.addVideo": "Video ekle", "homework.answer": "Yanıtınız", "homework.answerPlaceholder": "Yanıtınızı yazın...", "homework.pending": "İnceleniyor", "homework.pendingText": "Ödev gönderildi ve incelenmeyi bekliyor.", "homework.accepted": "Kabul edildi", "homework.acceptedText": "Ödev uzman tarafından kabul edildi.", "homework.revision": "Düzeltme gerekli", "homework.expertComment": "Uzman yorumu", "homework.statusUnavailable": "Ödev durumu geçici olarak kullanılamıyor.", "homework.title": "Ödev", "homework.canSend": "Gönderebilecekleriniz", "homework.submit": "Ödevi gönder", "homework.empty": "Bir yanıt ekleyin veya dosya iliştirin.", "homework.maxFiles": "En fazla 10 dosya ekleyebilirsiniz.", "homework.emptyFile": "«{name}» dosyası boş.", "homework.unsupported": "Bu dosya biçimi desteklenmiyor.", "homework.tooLarge": "«{name}» dosyası çok büyük.", "homework.preparing": "Hazırlanıyor...", "homework.sending": "Gönderiliyor...", "homework.uploading": "Yükleniyor: {current}/{total}...", "homework.sendError": "Ödev gönderilemedi. Tekrar deneyin.",
    "access.telegramTitle": "Kurs panelini Telegram'da açın", "access.telegramText": "Erişimi kontrol etmek için kapalı Telegram kanalındaki düğmeden kurs panelini açın.", "access.notFoundTitle": "Erişim bulunamadı", "access.notFoundText": "Bu kurs paneli yalnızca program katılımcılarına açıktır.", "access.errorTitle": "Erişim kontrol edilemedi", "access.errorText": "Kurs panelini kapatıp biraz sonra yeniden açın.", "access.expiredTitle": "Programa erişim sona erdi", "access.expiredText": "Programa erişim süreniz sona erdi. Uzatmak için aşağıdaki düğmeye basın.", "access.renew": "Erişimi uzat", "access.expiredUntil": "Erişim şu tarihe kadar açıktı: {date}",
    "renewal.expert": "Uzmanla iletişime geç", "renewal.support": "Destekle iletişime geç", "renewal.creating": "Talep oluşturuluyor…", "renewal.conflict": "Tamamlanmamış bir uzatma talebiniz zaten var. Paketi değiştirmek için destekle iletişime geçin.", "renewal.payError": "Ödeme sayfasına gidilemedi. Tekrar deneyin.", "renewal.ended": "Erişim sona erdi", "renewal.soon": "Erişim yakında sona erecek", "renewal.endedTitle": "Programa erişim sona erdi", "renewal.title": "Erişiminizi önceden uzatın", "renewal.lead": "Bir uzatma seçeneği belirleyin. Ödeme sonrasında uzman onayladığında erişim bir sonraki açılışta etkinleşir.", "renewal.expertLead": "Erişimi uzatmak için uzmana özel mesaj gönderin.", "renewal.wasUntil": "Erişim şu tarihe kadar açıktı: {date}", "renewal.until": "Erişim şu tarihe kadar açık: {date}", "renewal.days": "+{count} gün erişim", "renewal.choose": "{price} karşılığında seç"
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
